import json
import urllib
import httplib
import pprint

# Random names generated by http://listofrandomnames.com
names = """
Viviana
Leanne
Joe
Chieko
Mindi
Darell
Terese
Tricia
Keven
Tisa
Alpha
Jerrod
Otelia
Owen
Flavia
Anissa
Burton
Kellye
Ted
Kitty
""".split()

HOST = 'localhost'
PORT = 8000
URL = '/process/facebook'
last_index = 3
body = {'id': 1,
        'friend_list': [{'id': i + last_index, 'name': x} for i, x in enumerate(names)]}
        # 'like_list': [{'id': 1, 'name': 'like1'},
        #               {'id': 2, 'name': 'like2'},
        #               {'id': 3, 'name': 'like3'},
        #               {'id': 4, 'name': 'like4'},
        #               {'id': 5, 'name': 'like5'}]}

conn = httplib.HTTPConnection(HOST, PORT)
conn.request('POST', URL, json.dumps(body))
response = conn.getresponse()
print response.status
print response.reason
try:
    print pprint.pprint(json.loads(response.read()))
except (TypeError, ValueError):
    print 'No json response'
