import json
import urllib
import httplib
import pprint

# Random names generated by http://listofrandomnames.com
names = """
Viviana
Leanne
Joe
Chieko
Mindi
Darell
Terese
Tricia
Keven
Tisa
Alpha
Jerrod
Otelia
Owen
Flavia
Anissa
Burton
Kellye
Ted
Kitty
""".split()

HOST = 'localhost'
PORT = 8000
URL = '/process/twitter'
last_index = 21
body = {'id': 1000,
        'following_list': [{'id': i + last_index, 'name': x}
                          for i, x in enumerate(names)]}

conn = httplib.HTTPConnection(HOST, PORT)
conn.request('POST', URL, json.dumps(body))
response = conn.getresponse()
print response.status
print response.reason
try:
    print pprint.pprint(json.loads(response.read()))
except (TypeError, ValueError):
    print 'No json response'
